url: https://00e9e64bac8885a460fc88e6f9b55f2ff58dcd41553582fa8b-apidata.googleusercontent.com/download/storage/v1/b/flutter-web-app.appspot.com/o/index.html?qk=AD5uMEt13rS0nTKHWV3QMPqhXa1YM845CXUnLk1VgyHt-Zog8nD7m0LZSyLtqa7PA6_rK3cTePPBuUlFXt-HigPDXXAnGCblA_ynmxurIARs3BYQFJEn4UKVFfdN6-U9vnZnJJ1GM3pQhYpGqG7_kdmwozfA5Z_PeCjEHyvLVyD4ftzEV-LNhZP20PGv21L2Sick7jz7R7bKDlOtYc_o3WJtXgWGQuZBAQ6xIt_NcUCzSWkepb3kLDErnDtuV5ma5VaSZGN827M_RrD3op7rF7RV_42CHh-a86FqifMaxJXlD7WKPKG7tpPguRQbQO-oa4EHN7sI2bt9_tOvM-RKRGjqirmWWgBGLImLKQl1ZYF9xzGqW9yTEGHnJZ7QTrGA6L9g9YD9NPS7nOZq7BlHRqQMerBK5UDrlWs94jyO3YyteuR_POkehxfHkcKov9cHQArGlPxQjQ-pCna73mZHLxToJL6CgTJJe-MWBzBkKWAh7vCodglN9fWEgZGnGCvaJIwKvVBcM0cHnfzN-hPg33aeaZ4GyQKx3zpuRmzbltDFaJfTLsQoucKuQ9e3CsQjGLMXSTEtBbtKfcSoFc-L1o29KD3OcFaSoqEjFEz9oAgoIt44sXLbQdi6LLrvaC5d5s8QG_Vxu7yctCgdXGNg5rpUzMSEppvCzjthO8XEDclkFYeM2AA0Akhxy4flmUKLHdFvVN6pVTvzAOhlUlLhjd8JoP3xXgGyLMI0dOJmsR7FjdKJJise5ejQZQeW2GTIM8Nh4OFidVp2fJunx2ePhVrlHd4vq0HZSA
title: Empty app
geolocation: true
notifications: true
fcm_topic: main
app_bar:
  visible: true
  color: 7e57c2
